export default {
  CHANGE_MODE: 'CHANGE_MODE',
  CHANGE_COLOR: 'CHANGE_COLOR',

  FETCH_TWEETS_START: 'FETCH_TWEETS_START',
  FETCH_TWEETS_SUCCESS: 'FETCH_TWEETS_SUCCESS',
  FETCH_TWEETS_FAILD: 'FETCH_TWEETS_FAILD',

  SEND_TWEET_START: 'SEND_TWEET_START',
  SEND_TWEET_SUCCSESS: 'SEND_TWEET_SUCCSESS',
  SEND_TWEET_FAILD: 'SEND_TWEET_FAILD',

  AUTH_INIT_START: 'AUTH_INIT_START',
  AUTH_USER_START: 'AUTH_USER_START',
  AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
  AUTH_USER_FAILD: 'AUTH_USER_FAILD',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILD: 'UPDATE_USER_FAILD',
};
